Interactive list
MeqdamAlqudah/To-Do-List pull request #2
Opened 2021-12-02 23:09 UTC by MeqdamAlqudah

1-Add a modulo called interactively
2-Export and import a function that changes the value of the checkbox

2021-12-02 23:18 UTC, carlos-ssh requested changes
# 🦺 🚧 🚥 CHANGES REQUIRED 🚥 🚧 🦺
#

Hi @MeqdamAlqudah , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._ 


![changesrequested](https://user-images.githubusercontent.com/22258274/139840240-ea0d564a-492a-44e3-87af-8d5830ab0d6d.gif)
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-02 23:18 UTC, carlos-ssh commented on src/index.js
> +  image.setAttribute('src', 'icons/delete.png');
Your image isn't displaying well kindly fix it and request another code review.
<img width="1552" alt="Screen Shot 2021-12-02 at 17 17 01" src="https://user-images.githubusercontent.com/22258274/144518171-fc54d347-1263-4946-bdea-51a4333fa3c1.png">

2021-12-02 23:41 UTC, Mihndim2020 requested changes
## Hi @MeqdamAlqudah, 

Great work on making the changes requested by a previous reviewer 👏 👏 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![stay-strong-youre-almost-there](https://user-images.githubusercontent.com/65852621/133678845-1b015b27-e9bc-4784-a316-bc699db8237a.jpg)

 # Status: Requires Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-02 23:41 UTC, Mihndim2020 commented on src/index.js
> +  image.setAttribute('src', 'icons/delete.PNG');
- [ ] As requested by the previous reviewer, the link to your delete icon is broken, please kindly fix that. See image below.
![deleteBtn](https://user-images.githubusercontent.com/65852621/144520053-226cab73-1660-48f7-93bc-cee4f54b0d2c.png)

2021-12-02 23:41 UTC, Mihndim2020 commented on README.md
> +![screenshot](./Capture.png)
- [OPTIONAL] The link to the screenshot image is broken, please kindly fix that, as it will make your readme file look more professional.

2021-12-03 09:18 UTC, TedLivist approved these changes
## STATUS: APPROVED ✔️ ✔️

Hi @MeqdamAlqudah,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-03 19:18 UTC, merged